spring:
  application:
    name: authentication-security

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update # 개발 중에는 update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  mail:
    host: sandbox.smtp.mailtrap.io
    port: 2525
    username: c255bf701866cb
    password: aa01921155c69d
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
        debug: true

  http:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

  thymeleaf:
    encoding: UTF-8

  messages:
    encoding: UTF-8

server:
  port: 8081
  tomcat:
    use-http-only-sessions: true
    uri-encoding: UTF-8
    relaxed-query-encoding: true
    relaxed-path-encoding: true

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type:
          descriptor:
            sql: trace


